### ISSUE TITLE
SendMessageChain发送包含某些连接的信息时无法发出，单独分离该链接后可正常发出

### ISSUE THREAD

**Issue by K4sumizawaMiyU** [KusaGumina/RedProtocolSharp#1]
![`@(H4@(}$LGH856BZ7QY{EQ](https://github.com/KusaGumina/RedProtocolSharp/assets/126660738/c0fb2712-4646-4479-b73e-65b9df319c00)
![0GZ~C9DO ~1@URX0AC6C)BW](https://github.com/KusaGumina/RedProtocolSharp/assets/126660738/7c4c8927-3c55-42fd-af8a-ed4b5abe2596)
![MD5QF1Y%G{M(8%CVVP@C4VI](https://github.com/KusaGumina/RedProtocolSharp/assets/126660738/2c543104-3ec1-4338-8119-4e70a6eb9661)
![T%ASX %)1SF~I_U _8HS}S0](https://github.com/KusaGumina/RedProtocolSharp/assets/126660738/544f5ade-8abe-4920-bd12-8914853ff0e6)
下为不添加url发送结果
![5HT3LW57EJ}59YI7Y59VPQ9](https://github.com/KusaGumina/RedProtocolSharp/assets/126660738/41245b49-12af-41cd-96cb-85133e7c639b)
![_ %6 @UWP%RMK 8T8)PTU6N](https://github.com/KusaGumina/RedProtocolSharp/assets/126660738/55740c9b-9bfa-49d5-823e-c2fad8adc991)
补一张发送pixiv链接正常的图
![585XHG(C_W1$6H7G1$G}YT](https://github.com/KusaGumina/RedProtocolSharp/assets/126660738/e0f0cf3d-5914-4651-a7c5-e7eddd8049a6)

**Comment by Lilyltt** [comment]
请提供详细的信息帮助复现，包括:客户端截图，断下的发送的payload截图，以及你正常发送是否能发送目标链接，初步估测可能是这条链接消息被tx屏蔽导致你无法发送，非sdk问题
